# "Numpy"

### Import library numpy

In [1]:
import numpy as np

### Numpy version

In [48]:
np.__version__

'1.24.3'

### Numpy config

In [49]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ro_be/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ro_be/anaconda3\\Lib

### Get help

Get the information typing of any function

In [50]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) 

# Array vs List

### Define the list and the array

###### List

In [2]:
list_1=[1,2,3]
list_1

[1, 2, 3]

###### Array

In [4]:
array_1=np.array([4,5,6])
array_1

array([4, 5, 6])

### Print each element

###### List

In [6]:
for e in list_1:
    print (e)

1
2
3


###### Array

In [8]:
for e in array_1:
    print(e)

4
5
6


### Append new element

###### List

Original list

In [10]:
list_1

[1, 2, 3]

New list

In [12]:
list_1.append(4)
list_1

[1, 2, 3, 4]

It's possible to add a new element just "summing" the original list + a new element between brackets

In [14]:
list_1 + [5]

[1, 2, 3, 4, 5]

###### Array

Isn't possible to use append in an array and using the + will sum the number we are trying to add to each number in the array.

Original array

In [15]:
array_1

array([4, 5, 6])

In [16]:
array_1 + np.array([4])

array([ 8,  9, 10])

That's called "broadcasting"

## Maths

#### Sum

###### List  + List

Original list

In [18]:
list_1

[1, 2, 3, 4]

New list

In [23]:
list_2= list_1 + [5,6,7,8]
list_2

[1, 2, 3, 4, 5, 6, 7, 8]

If we sum two list the new list will be the result of the second list appended to the first list

Is necessary to import the library operator and use the function add in order to sum two list 

In [26]:
from operator import add

In [28]:
list_3=list(map(add,list_1,[5,6,7,8]))
list_3

[6, 8, 10, 12]

In [37]:
[sum(e) for e in zip(list_1,[5,6,7,8])]

[6, 8, 10, 12]

###### Array + Array

Original array

In [20]:
array_1

array([4, 5, 6])

New array

In [22]:
array_2 = array_1 + np.array([7,8,9])
array_2

array([11, 13, 15])

Is not possible to sum a new array if the length is not the same

### Basic  math operations

#### List

Original list:

In [38]:
list_1

[1, 2, 3, 4]

In order to add a number to each element it is necessary to create an empty list and use a for loop to add the number to each element and append it to the new list and is the same with all the operators

Sum

In [39]:
list_sum=[]
for e in list_1:
    list_sum.append(e + 3)
list_sum

[4, 5, 6, 7]

Rest

In [42]:
list_rest=[]
for e in list_1:
    list_rest.append(e - 1)
list_rest

[0, 1, 2, 3]

Multiply

In [45]:
list_mult=[]
for e in list_1:
    list_mult.append(e * 2)
list_mult

[2, 4, 6, 8]

Division

In [46]:
list_div=[]
for e in list_1:
    list_div.append(e / 2)
list_div

[0.5, 1.0, 1.5, 2.0]

Power

In [47]:
list_pow=[]
for e in list_1:
    list_pow.append(e ** 2)
list_pow

[1, 4, 9, 16]

Square root

In order to use the square root function we gotta import the math library

In [48]:
import math

In [50]:
list_sqrt=[]
for e in list_1:
    list_sqrt.append(math.sqrt(e))
list_sqrt

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0]

Exponential

In [51]:
list_exp=[]
for e in list_1:
    list_exp.append(math.exp(e))
list_exp

[2.718281828459045, 7.38905609893065, 20.085536923187668, 54.598150033144236]

###### NOTE:
<p>
There is a lot of math operation we can use but essentialy all are the same

###### Array

Original array

In [52]:
array_1

array([4, 5, 6])

Sum

In [53]:
array_1 + 2

array([6, 7, 8])

Rest

In [55]:
array_1 - 1

array([3, 4, 5])

Multiplication

In [56]:
array_1 * 3

array([12, 15, 18])

Division

In [57]:
array_1 / 2

array([2. , 2.5, 3. ])

Power

In [58]:
array_1 ** 2

array([16, 25, 36])

alternatively we can use the power function included in the numpy library

In [61]:
np.power(array_1,2)

array([16, 25, 36], dtype=int32)

Exponential

In [62]:
np.exp(array_1)

array([ 54.59815003, 148.4131591 , 403.42879349])

###### NOTE:
<p>
There is a lot of functions available in the numpy library

# The dot product

###### Define two arrays

In [63]:
array_a=np.array([1,2])
array_a

array([1, 2])

In [64]:
array_b=np.array([3,4])
array_b

array([3, 4])

To use the dot function, declare an empty variable

In [65]:
dot=0
for a,b in zip(array_a,array_b):
    dot += a*b
dot

11

alternatively

In [67]:
dot=0
for e in range(len(array_a)):
    dot+= array_a[e]*array_b[e]
dot

11

Or

In [68]:
dot=np.sum(array_a*array_b)
dot

11

In [69]:
(array_a * array_b).sum()

11

Usinig the function dot in the numpy library

In [71]:
np.dot(array_a,array_b)

11

Or

In [74]:
array_a.dot(array_b)

11

In [75]:
array_b.dot(array_a)

11

In [76]:
array_a @ array_b

11

In [77]:
array_b @ array_a

11

# Speed test

### Import libraries

In [78]:
from datetime import datetime

###### Define variables

In [79]:
a=np.random.randn(100)
b=np.random.randn(100)
t=100000

###### List

Define the for loop that we will use to calculate de dot product in a list

In [80]:
def slow_dot_product(a,b):
    result=0
    for e,f in zip(a,b):
        result += e*f
        return result

Create a variable to save the current time and then rest the time when the code execute the for loop - the time time it finished

In [87]:
t0=datetime.now()
for i in range(t):
    slow_dot_product(a,b)
dt1=datetime.now()-t0
dt1.total_seconds()

0.076801

###### Array

Create a variable to save the current time and then rest the time when the code execute the for loop - the time time it finished

In [86]:
t0= datetime.now()
for i in range(t):
    a.dot(b)
dt2=datetime.now()-t0
dt2.total_seconds()

0.088078

Make a division to calculate the diference in seconds

In [95]:
dt1.total_seconds()/dt2.total_seconds()

1.3073889845460536

###### Run the code at the same time to calculate it

In [94]:
t0=datetime.now()
for i in range(t):
    slow_dot_product(a,b)
dt1=datetime.now()-t0

t0= datetime.now()
for i in range(t):
    a.dot(b)
dt2=datetime.now()-t0

dt1.total_seconds()/dt2.total_seconds()

1.3073889845460536

# Matrices

How would you represent a matrix without numpy? 

###### Doing a list of list

In [96]:
L=[[1,2],[3,4]]
L

[[1, 2], [3, 4]]

To access to an specific value just type it as a regular list, for example we want the 2 in the first list

In [97]:
L[0][1]

2

###### Numpy array

In [99]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

To access to an specific value just type it as a regular list, for example we want the 2 in the first list

In [100]:
A[0][1]

2

Or

In [102]:
A[0,1]

2

Select one column

In [104]:
A[:,0]

array([1, 3])

use A.T to print a 2x2 array

In [107]:
A.T

array([[1, 3],
       [2, 4]])

### Maths

Can be used in both list and array

###### Exponential

In [108]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [109]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

###### Square Root

In [110]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [111]:
np.sqrt(L)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

###### Multiply arrays

Create a new array to multiply

In [114]:
B=np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

Array A

In [115]:
A

array([[1, 2],
       [3, 4]])

Multiply A*B

In [117]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

The array has to match the number of columns x num of files

# Solving linear Systems

### Define the arrays

In [4]:
A=np.array([[1,1],[1.5,4]])
B=np.array([2200,5050])

In [5]:
A

array([[1. , 1. ],
       [1.5, 4. ]])

In [6]:
B

array([2200, 5050])

### Solve function

In [8]:
np.linalg.solve(A,B)

array([1500.,  700.])

### Manually

In [9]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])

# Generating data

### Zeros

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Ones

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Identity

In [18]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Random number

In [21]:
np.random.random()

0.6771723319874257

In [23]:
np.random.random((2,3))

array([[0.08965937, 0.08921876, 0.42846923],
       [0.09193641, 0.26779466, 0.49157068]])

### Random number mixing negative and positive values

In [24]:
np.random.randn(2,3)

array([[ 0.188831  , -0.90349207, -0.68044042],
       [ 1.224147  , -0.97503051, -2.67590001]])

### Random integer numbers

In [44]:
np.random.randint(60,100,size=(5,5))

array([[83, 91, 65, 86, 82],
       [62, 74, 95, 76, 69],
       [91, 90, 93, 82, 69],
       [96, 71, 98, 72, 63],
       [80, 61, 75, 74, 76]])

In [42]:
np.random.choice(100,size=(5,5))

array([[97, 69, 24, 90, 70],
       [74, 36,  4, 62, 95],
       [ 5, 51, 18, 58, 95],
       [93, 19, 16,  3, 81],
       [52, 94, 10, 36, 63]])

### Mean,variance and stardard deviation

In [34]:
R=np.random.rand(10000)

###### Mean

In [35]:
R.mean()

0.4991562028241187

###### Mode

In [39]:
R.var()

0.08439811265783229

###### Standard deviation

In [40]:
R.std()

0.29051353265869095

# Exercises

Original link: https://codesolid.com/numpy-practice-questions-to-make-you-an-expert/

### 1-D numpy array exercises

Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10

In [114]:
array_10_100_10=np.arange(10,100,10)
array_10_100_10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

How could you create the same NumPy array using a Python range and a list?

In [118]:
list_10_100_10=[]
for e in range(10,100,10):
    list_10_100_10.append(e)
list_10_100_10

[10, 20, 30, 40, 50, 60, 70, 80, 90]

How might you create a NumPy array of the capital letters, A-Z?

In [125]:
import string
capital_letters_array=np.array(list(string.ascii_uppercase))
capital_letters_array

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

How would you create a ten-element NumPy array object of all zeros

In [127]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

What function would return the same number of elements, but of all ones?

In [128]:
#ones
array_ones=np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

How could you create a ten-element array of random integers between 1 and 5 (inclusive)?

In [129]:
random_array_1_5=np.random.randint(1,5,size=(10))
random_array_1_5

array([2, 3, 3, 4, 1, 2, 1, 1, 1, 3])

How can you create a normal distribution of 10 numbers, centered on 5?

In [131]:
normal_distribution=np.random.normal(5,1,10)
normal_distribution

array([5.89073002, 5.12707731, 4.35996958, 4.44708548, 3.54526912,
       6.23250091, 3.93827065, 5.72043282, 4.79399748, 4.61834033])

What code would create an array of 10 random numbers between zero and one?

In [136]:
random_number_0_1=np.random.rand(10)
random_number_0_1

array([0.0271813 , 0.5057899 , 0.53419389, 0.68070116, 0.72193814,
       0.05119129, 0.04525998, 0.89955975, 0.5972212 , 0.62771228])

### Creating and Using Multidimensional Arrays

Consider an array named “myarray” that is displayed as in the block below. Return the value 7

* ([[ 1,  2,  3,  4],
*  [ 5,  6,  7,  8],
*  [ 9, 10, 11, 12]])

In [20]:
myarray=(np.arange(1,13)).reshape((3,4))
myarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
myarray[1][2]

7

Given myarray as shown above, what is the dimension of the array?

In [24]:
myarray.ndim

2

An array of three arrays of four elements each like this has twelve elements, of course. How could you create a new array consisting of two arrays of six elements each?

In [30]:
array_3_4=(np.arange(1,13)).reshape((3,4))
array_3_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
new_array_3_2=np.array_split(array_3_4,2,axis=1)
arrray_split1=new_array_3_2[0]

arrray_split2=new_array_3_2[1]

In [37]:
arrray_split1

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [39]:
arrray_split2

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

How could you create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10?

In [42]:
random_array_3_4=np.random.randint(1,10,size=(3,4))
random_array_3_4

array([[5, 8, 4, 6],
       [7, 1, 6, 6],
       [6, 5, 7, 7]])

How could you create an array of the same size and shape as the previous one, filled with 64-bit integer zeros?

In [57]:
zeros_array_3_4=(np.zeros(12)).reshape((3,4))
zeros_array_3_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Given an array, named "arr“, that looks like:

* [[0, 1, 2],
*  [3, 4, 5]]

How could you display an array that looks like:

* [[0, 3],
*  [1, 4],
*  [2, 5]]

In [62]:
arr=np.array([[0,1,2],[3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

### Indexing and Slicing Two-Dimensional Arrays

Given the following four_by_five array. Write a statement that prints the first row. (It will be a five-element array)

* [[ 1,  2,  3,  4,  5],
*  [ 6,  7,  8,  9, 10],
*  [11, 12, 13, 14, 15],
*  [16, 17, 18, 19, 20]]

In [80]:
four_by_five=(np.arange(1,21)).reshape((4,5))
four_by_five

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [81]:
four_by_five[0]

array([1, 2, 3, 4, 5])

Using the same four_by_five array.Write an expression to print the last row. (It will be a five-element array).

In [82]:
four_by_five[-1]

array([16, 17, 18, 19, 20])

Using the same four_by_five array.Print the 14 value

In [84]:
four_by_five[2][3]

14

Using the same four_by_five array.How could you display the first column? It will be a (four-element array ending with 16.)

In [95]:
four_by_five[:,0]

array([ 1,  6, 11, 16])

Using the same four_by_five array.Display the last two colums

In [104]:
four_by_five[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

Using the same four_by_five array.Write an expression to return the last two columns of the middle two rows.

In [105]:
four_by_five[1:3,3:]

array([[ 9, 10],
       [14, 15]])